% 1. Set working directory
cd('C:\Users\rocsa\Desktop\Universitat\TFG\Data');

% 2. Create and run each BEAR model

% Model 1 - df1_eu.xlsx
m1 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df1_eu.xlsx', ...
    'startdate', '2014m2', ...
    'enddate', '2019m12', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'lags', 3, ...
    'results_sub', 'results_1_eu', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 0, ...
    'F', 0);
BEARmain(m1);

% Model 2 - df2_eu.xlsx
m2 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df2_eu.xlsx', ...
    'startdate', '2020m1', ...
    'enddate', '2023m3', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'iobs',1,...
    'lags', 3, ...
    'results_sub', 'results_2_eu', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 0, ...
    'F', 0);
BEARmain(m2);

% Model 3 - df3_eu.xlsx
m3 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df3_eu.xlsx', ...
    'startdate', '2023m4', ...
    'enddate', '2025m4', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'iobs',1,...
    'lags', 3, ...
    'results_sub', 'results_3_eu', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 0, ...
    'F', 0);
BEARmain(m3);

% Model 4 - df1_us.xlsx
m4 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df1_us.xlsx', ...
    'startdate', '2014m2', ...
    'enddate', '2019m12', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'lags', 3, ...
    'results_sub', 'results_1_us', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 0, ...
    'F', 0);
BEARmain(m4);

% Model 5 - df2_us.xlsx
m5 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df2_us.xlsx', ...
    'startdate', '2020m1', ...
    'enddate', '2023m3', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'iobs',1,...
    'lags', 3, ...
    'results_sub', 'results_2_us', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 1, ...
    'F', 0);
BEARmain(m5);

% Model 6 - df3_us.xlsx
m6 = BEARsettings('BVAR', ...
    'frequency',3, ...
    'ExcelFile', 'df3_us.xlsx', ...
    'startdate', '2023m4', ...
    'enddate', '2025m5', ...
    'varendo', 'INTEREST_RATE INFLATION OUTPUT_GAP', ...
    'prior', 'Inw_univariate', ...
    'const',0,...
    'iobs',1,...
    'lags', 3, ...
    'results_sub', 'results_3_us', ...
    'IRFperiods', 8, ...
    'IRFt', 'Sign', ...
    'FEVD', 0, ...
    'HDall', 0, ...
    'F', 0);
BEARmain(m6);